[platformio]

; Universal all boards
src_dir = .
default_envs = t-camera-sim
;default_envs = esp32-cam

[env:esp32-cam]
;platform = espressif32@6.3.0
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = dio_opi
monitor_speed = 115200
upload_speed = 921600
board_build.psram = true
platform_packages =
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.3

lib_deps = 
	adafruit/Adafruit NeoPixel @ ^1.12.2
	bodmer/TFT_eSPI

build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=0

[env:t-camera-sim]
platform = espressif32
framework = arduino
board_build.arduino.memory_type = dio_opi
board_build.psram = true
upload_speed =  921600
monitor_speed = 115200
extends = env
board = esp32s3box
platform_packages =
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.3

monitor_filters =
	default
	esp32_exception_decoder

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_TTGO_T_CAM_SIM

lib_deps =
     arduino-libraries/ArduinoHttpClient @ ^0.5.0
     knolleary/PubSubClient @ ^2.8
     vshymanskyy/TinyGSM @ ^0.11.7
    
    ;https://github.com/nikil511/TinyGSM.git
    ;       StreamDebugger
    ;       CRC32
    ;       Thingsboard
    ;       ArduinoHttpClient
    ;       PubSubClient
    ;       ArduinoJSON
lib_ignore = 
    TFT_eSPI
    ArduinoHttpClient

board_build.partitions = default_16MB.csv
board_build.filesystem = spiffs
