#ifndef TSM_PROXY_ERROR_CODE_
#define TSM_PROXY_ERROR_CODE_

#define SUCCESS "00"
#define	BAD_REQUEST "01"
#define	POST_ISSUANCE_ERROR "03"
#define	APPLET_IS_NOT_INSTALLED "30"
#define	UNAVAILABLE_PHONE_NUMBER "31"
#define	PHONE_NUMBER_CHANGED "32"
#define	NO_AVAILABLE_SECURE_ELEMENT "42"
#define	NO_TARGET_SECURE_ELEMENT "41"
#define	NETWORK_NOT_AVAILABLE "81"
#define	SERVER_CONNECTION_FAIL "82"
#define	SERVER_BUSY "83"
#define	INTERNAL_SERVER_ERROR "99"
#define	UNKNOWN_ERROR "100"
#endif
