///////////////////////////////////////////////////////////////
// Define
///////////////////////////////////////////////////////////////
#define REBOOT                      "Board Reboot"
#define UART_INIT                   "kss_kose_uart_init"
#define UART_TRANSCEIVE             "kss_kose_uart_transceive"
#define UART_CLOSE                  "kss_kose_uart_close"
#define SESSION_CREATE              "kss_kose_session_create"
#define SESSION_OPEN                "kss_kose_session_open"
#define SESSION_CLOSE               "kss_kose_session_close"
#define APDU_SELECT_AID             "Kose_API_Select"
#define APDU_GET_RANDOM             "Kose_API_GetRandom"
#define APDU_INITIALIZE_UPDATE      "Kose_API_Initialize_Update"
#define APDU_EXTERNAL_AUTHENTICATE  "KOSE_API_External_Authenticate"
#define APDU_STORE_DATA             "KOSE_API_StoreData"
#define APDU_PUT_KEY                "KOSE_API_PutKey"
#define APDU_ENCRYPT_DECRYPT_CDATA_ENC  "Kose_API_EncryptData"
#define APDU_ENCRYPT_DECRYPT_CDATA_DEC  "Kose_API_DecryptData"
#define APDU_GENERATEKEY            "Kose_API_GenerateKey"
#define KEY_STORE_GET_DATA          "kss_key_store_get_data"
#define KEY_STORE_SET_KEY           "kss_key_store_set_key"
#define KEY_STORE_DATA              "kss_key_store_data"
#define RANDOM_GEN                  "kss_kose_rng"
#define MBEDTLS_VERIFY_SIGN         "kss_mbedtls_verify_sign"
#define GENERATE_KEY                "kss_key_store_generate_key"
#define SE_PROVISIONING             "se_provisioning"
#define AWS_IOT_DEMO                "aws_iot_demo_main"
#define GEN_CSR                     "gen_csr"
#define CHECK_SE                    "check_se"
#define REGISTER_SE                 "register_se"
#define REGISTER_DEVICE             "register_device"
#define ISSUE_APPLET                "issue_applet"
#define EXCHANGE_SERVICE_DATA       "exchange_service_data"
#define DELETE_APPLET               "delete_applet"
#define GSMCALLBACKRESPONSE         "gsmcallbackresponse"
#define API_KSS_SYMMETRIC_ENCRYPT   "kss_symmetric_encrypt"
#define API_KSS_SYMMETRIC_DECRYPT   "kss_symmetric_decrypt"

/** Select number of menu */
#define REBOOT_NUM                          "0.0"
#define UART_INIT_NUM                       "1.1"
#define UART_TRANSCEIVE_NUM                 "1.2"
#define UART_CLOSE_NUM                      "1.3"
#define SESSION_CREATE_NUM                  "2.1"
#define SESSION_OPEN_NUM                    "2.2"
#define SESSION_CLOSE_NUM                   "2.3"
#define APDU_SELECT_AID_NUM                 "3.1"
#define APDU_GET_RANDOM_NUM                 "3.2"
#define APDU_INITIALIZE_UPDATE_NUM          "3.3"
#define APDU_EXTERNAL_AUTHENTICATE_NUM      "3.4"
#define APDU_STORE_DATA_NUM                 "3.5"
#define APDU_PUT_KEY_NUM                    "3.6"
#define APDU_ENCRYPT_DECRYPT_CDATA_ENC_NUM  "3.7"
#define APDU_ENCRYPT_DECRYPT_CDATA_DEC_NUM  "3.8"
#define APDU_GENERATEKEY_NUM                "3.9"
#define KEY_STORE_GET_DATA_NUM              "4.1"
#define KEY_STORE_SET_KEY_NUM               "4.2"
#define KEY_STORE_DATA_NUM                  "4.3"
#define GENERATE_KEY_NUM                    "4.4"
#define API_KSS_SYMMETRIC_ENCRYPT_NUM       "4.5"
#define API_KSS_SYMMETRIC_DECRYPT_NUM       "4.6"
#define RANDOM_GEN_NUM                      "5.1"
#define MBEDTLS_VERIFY_SIGN_NUM             "9.1"
#define SE_PROVISIONING_NUM                 "10.1"
#define AWS_IOT_DEMO_NUM                    "11.1"
#define GEN_CSR_NUM                         "12.1"
#define CHECK_SE_NUM                        "13.1"
#define REGISTER_DEVICE_NUM                 "14.1"
#define REGISTER_SE_NUM                     "15.1"
#define ISSUE_APPLET_NUM                    "16.1"
#define EXCHANGE_SERVICE_DATA_NUM           "17.1"
#define DELETE_APPLET_NUM                   "18.1"
#define GSMCALLBACKRESPONSE_NUM             "19.1"

#define MENU_TEXT_SIZE  50